apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cd-pipeline-run-
spec:
  pipelineRef:
    name: cd-pipeline
  params:
    - name: repo-url
      value: "https://github.com/mohamudadildev-ai/devops-capstone-project.git"
    - name: branch
      value: main
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
